import xarray as xr
import numpy as np
from typing import List
from pathlib import Path
from xarray import DataArray, Dataset
import matplotlib.pyplot as plt

from .labels import COMP_LABELS
from .utils import *

CUT_AXIS_LABELS = {
    # grid type: Name, Name, unit, unit, Longname, Longname
    "spherical": ["Theta", "Phi", "deg", "deg", "$\\theta$", "$\phi$"],
    "planar or surface": ["Rho", "Theta", "distance", "deg", "$\\rho$", "$\\theta$"],
    "cylindrical": ["Z", "Phi", "distance", "deg", "Z", "$\\phi$"]
}


def cut(file_names: List[str], data_name: str = None) -> DataArray:
    if data_name is None:
        data_name = file_names[0].split('.')[0]
    dat_list = []
    for file_name in file_names:
        path = Path(file_name)
        if not path.is_file():
            raise Exception("File not found:" + file_name)

        extension = path.suffix
        match extension:
            case ".cut":
                dat_list.append(readcut(file_name, data_name))
            case ".nc":
                dat_list.append(xr.open_dataarray(file_name))

    if len(dat_list) > 1:
        cut_data = xr.combine_by_coords(dat_list, combine_attrs="drop_conflicts")
    else:
        cut_data = dat_list[0]
    return cut_data


def readcut(file_name: str, data_name: str = None) -> xr.DataArray:  # FIX ICUT DICTIONARY
    """
    Read .cut file generated by GRASP. 
    1. The data are organized per frequency and cut. Read block by block.
    2. Allocate data into multidimensional numpy array
    3. Create multidimensional xarray to facilitate the access of the data.

    References: 
    - GRASP manual: F2.1 Field Data in Cuts (p. 1056)

    Remark: 
    - we assume that for each frequency and cut, there is the same number of data points.
    - in case that should not be the case, the script must be rewritten!

    """

    if data_name is None:
        data_name = file_name.split('.')[0]

    with open(file_name, 'r') as file_cut:
        lines = file_cut.readlines()

    # Data from different cuts are stored one after the other.
    # Every cut is supposed to have the same number of data points.
    # Read-off common information from first cut's header.
    # Define suggested labels for using in plots.
    line = lines[1].split()
    v_ini, v_inc, v_num, _, icomp, icut, ncomp = [float(s) if '.' in s else int(s) for s in line]
    attributes, cut_type = check_grid_or_cut_type(icomp, ncomp, icut, "cut")
    x_name, rot_name, x_unit, rot_unit, xlname, rot_lname = CUT_AXIS_LABELS[cut_type][:]
    x_vals = np.linspace(v_ini, v_ini + (v_num - 1) * v_inc, v_num)

    # Read header information of the different cuts: cut orientation
    no_of_cuts = len(lines) // (v_num + 2)
    cut_orientation = [0.] * no_of_cuts
    for cut_index in range(no_of_cuts):
        cut_start = cut_index * (v_num + 2)
        line = lines[cut_start + 1].split()
        cut_orientation[cut_index] = float(line[3])

    # The cut file format does not tell us how many frequencies there are in the file, so we need to improvise
    cut_orientation_set = set(cut_orientation)
    no_of_frequencies = len(cut_orientation) // len(cut_orientation_set)
    if no_of_frequencies != 1:
        cut_orientation = list(cut_orientation_set)
        no_of_cuts = no_of_cuts // no_of_frequencies

    # Allocate data in multidimensional array: cut x datapoints_along_cut x field x frequency
    data = np.full(shape=(no_of_cuts, v_num, ncomp, no_of_frequencies), fill_value=complex(np.nan, np.nan), dtype=complex)
    for frequency_index in range(no_of_frequencies):
        for cut_index in range(no_of_cuts):
            cut_start = (frequency_index*no_of_cuts + cut_index) * (v_num + 2)
            for ii in range(v_num):
                line = lines[cut_start + ii + 2].split() # +2 means that first two lines are information
                for jj in range(0, len(line), 2):
                    data[cut_index, ii, jj // 2, frequency_index] = complex(float(line[jj]), float(line[jj + 1]))

    # Allocate data and labels
    da = xr.DataArray(
        data=data,
        dims=[rot_name, x_name, "comp", "freq"],
        name=data_name,
        coords=[
            (rot_name, cut_orientation, {"units": rot_unit, "long_name": rot_lname}),
            (x_name, x_vals, {"units": x_unit, "long_name": xlname}),
            ("comp", COMP_LABELS[cut_type][icomp][0:ncomp], {"long_name": "Field component"}),
            ("freq", np.arange(0, no_of_frequencies))
        ],
        attrs=dict(
            filename=file_name,
            cut_type=cut_type,
            n_of_f=[no_of_frequencies, "number of frequencies"],
            icomp=[icomp, attributes[0][icomp]],
            ncomp=[ncomp, attributes[1][ncomp]],
            icut=[icut, attributes[3][icut]]
        ),
    )

    print(da.to_series())

    return da


def plotcut(cut_array: xr.DataArray) -> list[plt.Line2D]:
    # Checking for the largest coordinate array, assuming that to be the x-axis
    check_coords = cut_array.sizes
    x_axis = max(check_coords, key=lambda key: check_coords[key])
    lplot_handles = []
    for i in cut_array.coords['freq'].values:
        plot_cut = cut_array.sel(freq=i)
        lplot = plot_cut.plot.line(x=x_axis)
        lplot_handles.append(lplot)
        plt.show()
    return lplot_handles
