import pint
import numpy as np
import xarray as xr
from pathlib import Path

from . import labels
from .. import torfile

def readcut(cutfilepath: str, torfilepath: str = '', tordict: dict = {}, 
            userinfo: dict = {}) -> xr.DataArray:
    """
    
    Example
    -------
    
    from pycra import torfile
    from pycra.fields import cutfile
    
    # define directory where the data is stored
    directory = './offset_reflector/Job_01'
    
    # define field-data
    cutfilepath = os.path.join(directory, 'spherical_cut_nearfield_H.cut')
    
    # define torfile
    torfilepath = os.path.join(directory, 'Job_01.tor')
    
    # ev. read torfile (faster when several files shall be read)
    tordict = torfile.tor2dict(torfilepath)
    
    # If torfile is not available: manually define frequencies
    speedoflight = 299792458
    wavelengths = [0.03] # say we choose only one frequency
    freqs = [speedoflight/wavelength for wavelength in wavelengths] # yields: [9993081933.333334]
    
    # If torfile is not available: create dictionary with relevant information
    userinfo = {
        'class_name': 'spherical_cut',                  # (required)
        'field_name': 'h_field',                        # (required)
        'coordinate_system_name': 'single_cut_coor',    # (optional)
        'field_region_distance_m': 1,                   # (optional)
        'freqs_Hz': [9993081933.333334]                 # (optional)
    }
    
    # Read the field-data. The following three methods give the same result
    da = cutfile.readcut(cutfilepath, torfilepath=torfilepath)
    da = cutfile.readcut(cutfilepath, tordict=tordict)
    da = cutfile.readcut(cutfilepath, userinfo=userinfo)
    
    Inputs
    ------
    
    --> cutfilepath = './offset_reflector/Job_01/spherical_cut_farfield_E.cut'
    
    One of the following inputs:
    --> torfilepath = './offset_reflector/Job_01/Job_01.tor' 
    --> tordict = torfile.tor2dict(torfilepath)
    --> userinfo = {
            'class_name': 'spherical_cut',                  # (required)
            'field_name': 'h_field',                        # (required)
            'coordinate_system_name': 'single_cut_coor',    # (optional)
            'field_region_distance_m': 1,                   # (optional)
            'freqs_Hz': [9993081933.333334]                 # (optional)
        }
        
    Implemented options for required userinfo-input. 
    class_name: [field_name options]
    --> 'spherical_cut': ['e_field', 'h_field'],
    --> 'planar_cut': ['e_field', 'h_field'],
    --> 'cylindrical_cut': ['e_field', 'h_field'],
    --> 'surface_cut': ['incident_e_field', 'incident_h_field', 'reflected_e_field', 'reflected_h_field', 'currents']
    
    
    Introduction
    ------------
    
    Ticra tools 23.1.0 Manual: 2078, 3248
    
    The file is generated by objects of the classes Spherical Cut, Planar Cut, Sur-
    face Cut, RCS Cut, and Cylindrical Cut for storing field data in cuts. The file
    extension is .cut.
    
    Numerical data and some information is stored in the cut-file.
    Auxiliary information (including relevant ones) is stored in the tor-file.
    The auxiliary information can also be provided by the user.
    
    V_INI - Initial value.
    V_INC - Increment.
    V_NUM - Number of values in cut.
    C     - Constant.
    ICOMP - Polarisation control parameter.
    ICUT  - Control parameter of cut.
    NCOMP - Number of field components.

    Frequencies and cuts are stacked (stored one after the other):
      freq1 - fix1 (varying vs. field components)
            - fix2 (varying vs. field components)
            - ...
      freq2 - fix1 (varying vs. field components)
            - fix2 (varying vs. field components)
            - ...

    Every cut (representing fix coordinate, e.g. phi) is organized as follows:
    1. line with comment
    2. varying coordinate (e.g. theta) x field data (e.g. electric field)
      Field data in cuts
      -0.4500000000E+02  0.1000000000E+00  901  0.0000000000E+00    3    1    2
      -0.1155179706E-15 -0.5496340760E-15 -0.4996140097E+00 -0.1135992391E-01
      -0.9444915142E-16 -0.5453101338E-15 -0.5001052232E+00 -0.6748178987E-02
      ...
    
    To be added:
    ------------
    
    - check whether first line of header is comment!
    - spherical cut (p. 3249), spherical grid (p. 3254):
      ICOMP = 51, 52, 53 (RCS)
      NCOMP = 5
    - planar grid (p. 3256/3259):
      ICOMP = 3256 (complex Poynting vector)
    - Coupling system (cuts, grid, one_cut; coordinates>labels etc.)
    - Frequency Group
    - ...
    
    Further comments to be removed at some point
    --------------------------------------------
    
    Torfile/user
    - class_name : spherical_cut, surface_cut, ...
    - field_name : 'e_field', 'h_field', 'incident_e_field', 'incident_h_field', 'reflected_e_field', 'reflected_h_field', 'currents'
    
    Retrieved information
    - coor_sys : polar, conical, axial, radial, ... (different choices for different classes)
    - polarisation : linear, ...
    - frequency        
    - near_far
    - near_dist
    - e_h
    - file_name
    - file_format
    - comment

    spherical_cut
    - theta_range
    - phi_range
    - polarisation_modification

    planar_cut
    - rho_range
    - phi_range

    cylindrical_cut
    - z_range
    - phi_range

    - surface_cut
    - rho_range
    - phi_range
    - polarisation_and_phase_coor_sys
    - phase_adjustment
    - centre_offset

    """
    
    cutfilepath = Path(cutfilepath)
    if cutfilepath.suffix != '.cut':
        raise Exception('Cutfile extension must .cut (given file: %s)' % cutfilepath)

    # read cutfile to dictionary
    cutdict = cut2dict(cutfilepath)

    # load torfile to dictionary
    if torfilepath:
        tordict = torfile.tor2dict(torfilepath)
    elif tordict:
        pass
    elif userinfo:
        pass
    else:
        print('Provide either torfilepath, tordict or userinfo!')
    
    # combine cutfile and torfile/userinfo
    infodict = gather_information(cutdict, tordict, userinfo)
    relevant_keys = [
        'file_name', 'class_name', 'field_region', 'field_region_distance_m',
        'coordinate_system', 'coordinate_system_name', 'fix_coordinates', 'varying_coordinates', 
        'field_name', 'polarisation', 'field_components_mathnames', 'field_components_mathunits', 'field_components_unitsystem',
        'freqs_Hz', 'data']
    cutinfodict = {k:v for k,v in {**cutdict, **infodict}.items() if k in relevant_keys}

    # store data as Xarray
    da = dict2xarray(cutinfodict)

    return da

def cut2dict(cutfilepath: Path):
    """
    Read cutfile-data into dictionary. Comments:
    - Every cut is has the same number of data points.
    - Read-off common information from first cut's header.
    """

    with open(cutfilepath, 'r') as file_cut:
        lines = file_cut.readlines()

    line = lines[1].split()
    v_ini, v_inc, v_num, _, icomp, icut, ncomp = [float(s) if '.' in s else int(s) for s in line]
    
    # Read header information of the different cuts: cut orientation
    no_of_cuts = len(lines) // (v_num + 2)
    cut_coordinates = [0.] * no_of_cuts
    for cut_index in range(no_of_cuts):
        cut_start = cut_index * (v_num + 2)
        line = lines[cut_start + 1].split()
        cut_coordinates[cut_index] = float(line[3])

    # define coordinates
    fix_coordinates = sorted(list(set(cut_coordinates)))
    varying_coordinates = np.linspace(v_ini, v_ini + (v_num - 1) * v_inc, v_num)

    # preallocate data in multidimensional array: fix_coordinate x varying_coordinate x field x frequency
    nrfix = len(fix_coordinates) # = no_of_cuts // no_of_frequencies
    nrvarying = len(varying_coordinates) # = v_num
    nrfreqs = len(cut_coordinates) // len(fix_coordinates) # nr. of lines in each cut-block
    nrfields = ncomp # related to columns: #cols/2
    data = np.full(shape=(nrvarying, nrfix, nrfields, nrfreqs), fill_value=complex(np.nan, np.nan), dtype=complex)
    for frequency_index in range(nrfreqs):
        for fix_index in range(nrfix):
            fix_start = (frequency_index*nrfix + fix_index) * (v_num + 2)
            for ii in range(nrvarying):
                line = lines[fix_start + ii + 2].split() # +2 means that first two lines are information
                for jj in range(0, len(line), 2):
                    data[ii, fix_index, jj // 2, frequency_index] = complex(float(line[jj]), float(line[jj + 1]))

    cutdict = {
        'file_name': str(cutfilepath.resolve()),
        'cuttype': lines[0].strip(),
        #'v_ini': v_ini, ### needed?
        #'v_inc': v_inc, ### needed?
        #'v_num': v_num, ### needed?
        'icomp': icomp,
        'icut': icut,
        'ncomp': ncomp,
        'datacoords': ['varying','fix','field-component','frequency'], # just for remembering
        'fix_coordinates': fix_coordinates,
        'varying_coordinates': varying_coordinates,
        'data': data
    }

    return cutdict

def gather_information(cutdict: dict, tordict: dict = {}, userinfo: dict = {}) -> dict:
    """
    Combine data from cutfile + torfile/userinfo: dictionary with labels etc.
    """

    ureg = pint.UnitRegistry()

    if tordict:

        cutname = Path(cutdict['file_name']).stem
        
        # get class_name ('spherical_cut', ...)
        class_name = tordict[cutname]['class_name'] # spherical_cut, planar_cut, surface_cut and cylindrical_cut
        
        # check that the identified class_name is implemented (to avoid wheird errors)
        known_class_names = ['spherical_cut', 'planar_cut', 'surface_cut', 'cylindrical_cut']
        if not class_name in known_class_names:
            print('No such class_name: %s' % class_name)
            print('Implemented options include: %s' % known_class_names)
            raise
        
        # field ('e_field', 'h_field', 'reflected_e_field', 'currents', ...)
        if class_name == 'surface_cut':
            field_name = tordict[cutname]['field_type'] if 'field_type' in tordict[cutname].keys() else 'indicent_e_field'
        else:
            field_name = tordict[cutname]['e_h'] if 'e_h' in tordict[cutname].keys() else 'e_field'

        # coordinate system ('single_cut_coor', ...)
        coordinate_system_name = torfile.get_coordinate_system_name(tordict[cutname]) # e.g. single_cut_coor
            
        # near- vs. farfield
        if class_name in ['planar_cut','surface_cut','cylindrical_cut']:
            field_region = 'near'
        elif 'near_far' in tordict[cutname].keys(): # spherical_cut
            field_region = tordict[cutname]['near_far'].split(',')[0]
        else: 
            field_region = 'far'
                    
        # nearfield distance
        if class_name == 'surface_cut':
            field_region_distance_m = 0.
        elif field_region == 'far':
            field_region_distance_m = np.inf
        else:
            field_region_distance, field_region_distance_units = torfile.get_nearfield_distance(tordict, cutname)
            field_region_distance_m = (field_region_distance * ureg[field_region_distance_units]).to('m').magnitude            
            
        # frequency
        try:
            freqs_Hz = torfile.read_frequencies(tordict, objname=cutname)
            if len(freqs_Hz) != np.shape(cutdict['data'])[3]:
                print('Error with file: %s' % cutdict['file_name'])
                print('Caution! Frequency indications are inconsistent with the computed nr. of frequencies!')
                print('Remark: maybe save GRASP project and retry: \
                    (unlike the .cut file, the .tor is exported only when saving)!')
                raise
        except Exception as ee:
            print('Error with file: %s' % cutdict['file_name'])
            print('Complete frequency/wavelength reading from torfile.')
            print(ee)
            raise
                        
    elif userinfo:
        
        # TICRA TOOLS 23.1.0 p. 2079...
        class_name_options = labels.cut_type.keys() # ['spherical_cut', 'planar_cut', 'cylindrical_cut', 'surface_cut']
        field_name_options = {
            'spherical_cut': ['e_field', 'h_field'],
            'planar_cut': ['e_field', 'h_field'],
            'cylindrical_cut': ['e_field', 'h_field'],
            'surface_cut': ['incident_e_field', 'incident_h_field', 'reflected_e_field', 'reflected_h_field', 'currents']}
        
        # check user-defined class_name (e.g. 'surface_cut', ...)
        if 'class_name' not in userinfo.keys():
            print('Please provide "class_name":')
            print('Options: %s' % class_name_options)
            raise
        else: 
            class_name = userinfo['class_name']
            if class_name not in class_name_options:
                print('class_name "%s" not in options: %s' % (class_name, class_name_options))
                raise
            
        # check user-defined field_name (e.g. 'reflected_h_field', ...)
        if 'field_name' not in userinfo.keys():
            print('Please provide "field_name":')
            print('Options for %s: %s' % (field_name, field_name_options[class_name]))
            raise
        else: 
            field_name = userinfo['field_name']
            if field_name not in field_name_options[class_name]:
                print('field_name "%s" not in options: %s' % (field_name, field_name_options[class_name]))
                raise
        
        # coordinate system name
        coordinate_system_name = userinfo['coordinate_system_name'] if 'coordinate_system_name' in userinfo.keys() else '???'
        if not (type(coordinate_system_name) is str):
            print('"coordinate_system_name" must be string')
           
        # field_region and field_region_distance_m
        field_region_distance_m = userinfo['field_region_distance_m'] if 'field_region_distance_m' in userinfo.keys() else np.nan        
        if not ((type(field_region_distance_m) is int) | (type(field_region_distance_m) is float)):
            print('"nearfield_distance_m" must be numeric!')
        field_region = 'near' if cutdict['ncomp'] > 2 else 'far'
        if class_name == 'surface_cut':
            field_region_distance_m = 0.
        elif (field_region == 'far') & (field_region_distance_m != np.inf):
            print('far-field --> reset field_region_distance_m to infinity') 
            field_region_distance_m = np.inf
        else:
            pass
            
        
        # frequencies
        freqs_Hz = userinfo['freqs_Hz'] if 'freqs_Hz' in userinfo.keys() else [np.nan]*np.shape(cutdict['data'])[3]
        if len(freqs_Hz) != np.shape(cutdict['data'])[3]:
            print('Indicated nr. of frequencies (%d) in contrast with cut-file (%d)' % (len(freqs_Hz), np.shape(cutdict['data'])[3]))
            raise
        
    else:

        print('Please provide either torfile of user information.')
        raise

    # given all the properties: define labels from user manual
    coordinate_system = labels.cut_type[class_name][cutdict['icut']] # e.g. {'name': 'polar', 'coords': ('phi', 'theta'), 'units': ('deg', 'deg'), 'tex': ('\\phi', '\\theta')}
    polarisation = labels.cut_polarisation[class_name][cutdict['icomp']][0] # e.g. linear
    field_components_mathnames = labels.cut_polarisation[class_name][cutdict['icomp']][1] # e.g. ['E_{co}', 'E_{cx}', 'E_r']
    field_components_mathnames = field_components_mathnames[0:cutdict['ncomp']] # e.g. ['E_{co}', 'E_{cx}']
    
    # replace fieldnames
    # surface_cut: e.g. E_{i,\,co} --> H_{r,\,co}
    # all other cuts: e.g. E_{co} --> H_{co}
    if class_name == 'surface_cut': 
        if field_name == 'incident_h_field':
            field_components_mathnames = [el.replace(r'E', r'H') for el in field_components_mathnames]
        elif field_name == 'reflected_e_field':
            field_components_mathnames = [el.replace(r'E_{i',r'E_{r') for el in field_components_mathnames]
        elif field_name == 'reflected_h_field':
            field_components_mathnames = [el.replace(r'E_{i',r'E_{r') for el in field_components_mathnames]
            field_components_mathnames = [el.replace(r'E', r'H') for el in field_components_mathnames]
        elif field_name == 'currents':
            field_components_mathnames = [el.replace(r'E', r'I') for el in field_components_mathnames]
        else: # field_name == 'incident_e_field'
            pass
    elif field_name == 'h_field': 
            field_components_mathnames = [el.replace(r'E', r'H') for el in field_components_mathnames]
    else: # field_name == 'e_field'
        pass
    
    # determine units of the field components
    field_components_unitsystem, field_components_mathunits = labels.units_of_components(polarisation, field_region)
        
    # gather all the information
    inputinfodict = {
        'class_name': class_name, # torfile/user (required): e.g. spherical_cut (surface_cut)
        'field_name': field_name, # torfile/user (required): e.g. e_field (incident_e_field)
        'coordinate_system_name': coordinate_system_name, # torfile/user: e.g. single_cut_coor (optional)
        'field_region_distance_m': field_region_distance_m, # torfile/user: e.g. 6 (optional)
        'freqs_Hz': freqs_Hz} # torfile/user (optional)
    outputinfodict = {
        'coordinate_system': coordinate_system, # icut + class_name --> e.g. spherical_cut: polar, conical -->  {'name': 'polar', 'coords': ('phi', 'theta'), 'units': ('deg', 'deg'), 'tex': ('\\phi', '\\theta')}
        'polarisation': polarisation, # icomp + class_name --> e.g. spherical_cut: linear, total power, ...
        'field_region': field_region, # ncomp / torfile --> near_field / far_field
        'field_components_mathnames': field_components_mathnames, # ncomp + class_name + field_name --> e.g. spherical_cut: ['E_{co}', 'E_{cx}', 'E_r']
        'field_components_unitsystem': field_components_unitsystem, # icomp + class_name (polarisation & field_region) --> e.g. spherical
        'field_components_mathunits': field_components_mathunits} # icomp + class_name (polarisation & field_region)
    infodict = {**inputinfodict,**outputinfodict}

    return infodict

def dict2xarray(cutinfodict: dict) -> xr.DataArray:
    """
    store dictionary as Xarray
    
    https://docs.xarray.dev/en/latest/user-guide/plotting.html
    https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch03s03.html
    Xarray uses the coordinate name along with metadata: 
    - attrs.long_name 
    - attrs.standard_name
    - DataArray.name
    - attrs.units
   
    """

    # combine the information (x: fix coordinate, y: varying coordinate)
    xlabel = cutinfodict['coordinate_system']['coords'][0]
    ylabel = cutinfodict['coordinate_system']['coords'][1]
    xunits = cutinfodict['coordinate_system']['units'][0]
    yunits = cutinfodict['coordinate_system']['units'][1]
    xlabel_tex = cutinfodict['coordinate_system']['coords_math'][0]
    ylabel_tex = cutinfodict['coordinate_system']['coords_math'][1]
    xvals = cutinfodict['fix_coordinates']
    yvals = cutinfodict['varying_coordinates']
    compindice = ['a', 'b', 'c'][0:len(cutinfodict['field_components_mathnames'])]

    # prepare coordinates to assign to array
    coords_Y = ('Y', yvals, {'long_name': ylabel, 'texname': ylabel_tex, 'units': yunits})
    coords_X = ('X', xvals, {'long_name': xlabel, 'texname': xlabel_tex, 'units': xunits})
    coords_comp = ('comp', compindice, {
        'long_name': 'field comopnents',
        'field_type': cutinfodict['field_name'],
        'polarisation': cutinfodict['polarisation'],
        'names_math': cutinfodict['field_components_mathnames'],
        'units_math': cutinfodict['field_components_mathunits'], 
        'unitsystem': cutinfodict['field_components_unitsystem']})
    coords_freq = ('freq', cutinfodict['freqs_Hz'], {'long_name': 'frequency', 'units': 'Hz'})

    # # Remark: the following also works somehow
    # # # https://xarray.pydata.org/en/v0.12.2/quick-overview.html
    # newcomp = xr.DataArray(data = xvals, dims = ['X'],
    #     attrs = {'long_name': 'X-coordinate (fix)', 'name': xlabel, 'units': xunits, 
    #     'name_math': xlabel_tex, 'units_math': xunits_tex})

    da = xr.DataArray(
        # name = str(Path(cutinfodict['file_name']).stem,
        data = cutinfodict['data'],
        coords = [coords_Y, coords_X, coords_comp, coords_freq],
        attrs = {
            'filename': cutinfodict['file_name'],
            'class_name': cutinfodict['class_name'],
            'coordinate_system': cutinfodict['coordinate_system']['name'],
            'coordinate_system_name': cutinfodict['coordinate_system_name'],
            'field_region': cutinfodict['field_region'],
            'field_region_distance_m': cutinfodict['field_region_distance_m']})
    
    return da