import xarray as xr
from pathlib import Path

from .. import torfile
from . import gridfile_grdutils
from . import gridfile_h5utils

def readgrid(gridfilepath: str, torfilepath: str = '', tordict: dict = {}, 
             userinfo: dict = {}) -> xr.DataArray:
    """
    
    Example
    -------
    
    from pycra import torfile
    from pycra.fields import gridfile
    
    # define directory where the data is stored
    directory = './offset_reflector/Job_01'
    
    # define field-data
    gridfilepath = os.path.join(directory, 'spherical_grid_nearfield_uv_H.cut')
    
    # define torfile
    torfilepath = os.path.join(directory, 'Job_01.tor')
    
    # ev. read torfile (faster when several files shall be read)
    tordict = torfile.tor2dict(torfilepath)
    
    # If torfile is not available: manually define frequencies
    speedoflight = 299792458
    wavelengths = [0.03] # say we choose only one frequency
    freqs = [speedoflight/wavelength for wavelength in wavelengths] # yields: [9993081933.333334]
    
    # If torfile is not available: create dictionary with relevant information
    userinfo = {
        'class_name': 'spherical_grid',                 # (required)
        'field_name': 'h_field',                        # (required)
        'coordinate_system_name': 'single_cut_coor',    # (optional)
        'field_region_distance_m': 1,                   # (optional)
        'freqs_Hz': [9993081933.333334]                 # (optional)
    }
    
    # Read the field-data. The following three methods give the same result
    da = gridfile.readgrid(gridfilepath, torfilepath=torfilepath)
    da = gridfile.readgrid(gridfilepath, tordict=tordict)
    da = gridfile.readgrid(gridfilepath, userinfo=userinfo)
    
    Inputs
    ------
    
    --> gridfilepath = './offset_reflector/Job_01/spherical_cut_farfield_E.cut'
    
    One of the following inputs:
    --> torfilepath = './offset_reflector/Job_01/Job_01.tor' 
    --> tordict = torfile.tor2dict(torfilepath)
    --> userinfo = {
            'class_name': 'spherical_grid',                 # (required)
            'field_name': 'h_field',                        # (required)
            'coordinate_system_name': 'single_cut_coor',    # (optional)
            'field_region_distance_m': 1,                   # (optional)
            'freqs_Hz': [9993081933.333334]                 # (optional)
        }
        
    Implemented options for required userinfo-input. 
    class_name: [field_name options]
    --> 'spherical_grid': ['e_field', 'h_field'],
    --> 'planar_grid': ['e_field', 'h_field'],
    --> 'cylindrical_grid': ['e_field', 'h_field'],
    --> 'surface_grid': ['incident_e_field', 'incident_h_field', 'reflected_e_field', 'reflected_h_field', 'currents']
    
    Introduction
    ------------
    
    .grd: Ticra tools 23.1.0 Manual: 2109, 3253
    This format is used for storing field values in a rectangular grid. Files of this
    type are generated by objects of the classes Spherical Grid, Planar Grid, Sur-
    face Grid, Cylindrical Grid and RCS Grid, and the file extension is .grd.
    
    .h5: Ticra tools 23.1.0 Manual: 3261
    This format is used for storing field values in a rectangular grid using the bi
    nary HDF5 format https://www.hdfgroup.org/. Files of this type are gen-
    erated when certain commands, such as Get Field and Get Pattern, are called
    with targets of the classes Spherical Grid, Planar Grid, and Cylindrical Grid.
    The file extension is .h5.
    
    Numerical data and some information is stored in the cut-file.
    Auxiliary information (including relevant ones) is stored in the tor-file.
    The auxiliary information can also be provided by the user.
    
    To be added
    ----------- 
    - h5 processing
    - RCS Grid
    - KLIMIT != 0
    - Frequency Group, Wavelength Range, ...
    - Notice: For surface_grid: frequencies are not given in .grd file
    - ...
    
    Some other things
    -----------------
    
    # # define descriptions as did Roland
    # from .labels import COMP_LABELS, GRID_AXIS_LABELS
    # attributes, grid_type = utils.check_grid_or_cut_type(griddict['icomp'], griddict['ncomp'], griddict['igrid'], 'grid')
    # icomp_description = attributes[0][griddict['icomp']]
    # ncomp_description = attributes[1][griddict['ncomp']]
    # igrid_description = attributes[2][griddict['igrid']]

    # # component description
    # complabels = COMP_LABELS[grid_type][griddict['icomp']][0:griddict['ncomp']]
    
    # # define coordinate names and suggest corresponding labels for usage in plots
    # xname, yname, xunit, yunit, xlname, ylname = GRID_AXIS_LABELS[griddict['igrid']][:]

    # print(xcoords)
    # print(ycoords)
    # print(icomp_description)
    # print(ncomp_description)
    # print(igrid_description)
    # print(complabels)
    # print([xname, yname, xunit, yunit, xlname, ylname])
    # raise
    
    """
    
    gridfilepath = Path(gridfilepath) # convert string to pathlib object
    
    if gridfilepath.suffix == '.grd':
        
        # load torfile to dictionary
        if torfilepath:
            tordict = torfile.tor2dict(torfilepath)
        elif tordict:
            pass
        elif userinfo:
            pass
        else:
            print('Provide either torfilepath, tordict or userinfodict!')
        
        # read gridfile
        griddict = gridfile_grdutils.grid2dict_grd(gridfilepath)
                
        # combine grid- and torfile/userinfo
        infodict = gridfile_grdutils.gather_information(griddict, tordict, userinfo)        
        relevant_keys = [
            'file_name', 'class_name', 'field_region', 'field_region_distance_m',
            'coordinate_system', 'coordinate_system_name', 'ycoords', 'xcoords', 
            'field_name', 'polarisation', 'field_components_mathnames', 'field_components_mathunits', 'field_components_unitsystem',
            'freqs_Hz', 'data']
        gridinfodict = {k:v for k,v in {**griddict, **infodict}.items() if k in relevant_keys}
        
        # store data as Xarray
        da = dict2xarray(gridinfodict)
        
    elif gridfilepath.suffix == '.h5':
        
        raise Exception('Please finish implementation! (other information in file...)')
        gridinfodict = gridfile_h5utils.grid2dict_h5(gridfilepath)
        da = dict2xarray(gridinfodict)
        
    else:
        
        raise Exception('Gridfile extension must .grid or .h5 (given file: %s)' % gridfilepath)
    
    return da

def dict2xarray(gridinfodict: dict) -> xr.DataArray:
    """
    store dictionary as Xarray
    """

    # combine the information (x: fix coordinate, y: varying coordinate)
    xlabel = gridinfodict['coordinate_system']['coords'][0]
    ylabel = gridinfodict['coordinate_system']['coords'][1]
    xunits = gridinfodict['coordinate_system']['units'][0]
    yunits = gridinfodict['coordinate_system']['units'][1]
    xlabel_tex = gridinfodict['coordinate_system']['coords_math'][0]
    ylabel_tex = gridinfodict['coordinate_system']['coords_math'][1]
    xunits_tex = gridinfodict['coordinate_system']['units_math'][0]
    yunits_tex = gridinfodict['coordinate_system']['units_math'][1]
    xvals = gridinfodict['xcoords']
    yvals = gridinfodict['ycoords']
    compindice = ['a', 'b', 'c'][0:len(gridinfodict['field_components_mathnames'])]

    # prepare coordinates to assign to array
    coords_Y = ('Y', yvals, {'long_name': 'Y-coordinate', 'name': ylabel, 'units': yunits,
                             'name_math': ylabel_tex, 'units_math': yunits_tex})
    coords_X = ('X', xvals, {'long_name': 'X-coordinate', 'name': xlabel, 'units': xunits,
                             'name_math': xlabel_tex, 'units_math': xunits_tex})
    coords_comp = ('comp', compindice, {
        'long_name': 'field comopnents', 
        'field_type': gridinfodict['field_name'],
        'polarisation': gridinfodict['polarisation'],
        'names_math': gridinfodict['field_components_mathnames'],
        'units_math': gridinfodict['field_components_mathunits'], 
        'unitsystem': gridinfodict['field_components_unitsystem']})
    coords_freq = ('freq', gridinfodict['freqs_Hz'], {'long_name': 'frequency', 'units': 'Hz'})

    da = xr.DataArray(
        # name = str(Path(gridinfodict['file_name']).stem,
        data = gridinfodict['data'],
        coords = [coords_Y, coords_X, coords_comp, coords_freq],
        name = gridinfodict['file_name'],
        attrs = {
            'class_name': gridinfodict['class_name'],
            'coordinate_system': gridinfodict['coordinate_system']['name'],
            'coordinate_system_name': gridinfodict['coordinate_system_name'],
            'field_region': gridinfodict['field_region'],
            'field_region_distance_m': gridinfodict['field_region_distance_m']})

    return da